### ISSUE TITLE
RFC: Styled Map Typings (TypeScript plugin?)

### ISSUE THREAD

**Issue by scf4** [scf4/styled-map#11]
**Update:** Typings are available if you upgrade to `3.2.0-rc.1` with NPM. There shouldn't be any issues but I wanted to be safe hence the RC. Let me know if you encounter any issues, thanks!

Also: PRs for better typings are welcome!

---

Hey everyone

I'd like to add typings to Styled Map, but I'd really appreciate some input from the community.

At the moment we can do this:

```typescript
interface Props {
  primary?: boolean
  info?: boolean
}

const Button = styled.button<Props>`
  background-color: ${styledMap`
    primary: #0c0;
    info: #0cc;
    default: #ccc;
  `};
`;

<Button primary>Submit</Button>
```

But I'm quite sure it's impossible for TypeScript to recognize the props in the Styled Map pseudo CSS, so we'll likely have to settle with `any` type for the contents of the tagged template literal. What do you think?

However, it would be nice if we could detect them, and I think this could be accomplished with a TypeScript plugin. If anyone has any input or would like to contribute in some way, that would be awesome. 

Let me know your thoughts.

Thanks!

**Comment by scf4** [comment]
I’ve added basic types for now. They’ll be in the next release.

**Comment by dimitriirybakov** [comment]
@scf4 could you publish it?

**Comment by scf4** [comment]
@dimitriirybakov upgrade to `3.2.0-rc.1`. Let me know if you encounter any issues!
