### ISSUE TITLE
feature: How does styled-map integrate with styled-components theme?

### ISSUE THREAD

**Issue by udielenberg** [scf4/styled-map#12]
I wanted to congratulate you on a great idea for a library :)

I read in the readme you can work with themes.
But when it comes to integrating with *styled-components* or *emotion*
working with themes means integrating with its theme feature.

I was wondering if this is possible in styledMaps:
```
const myTheme = {
  buttonColor: {
    primary: ({ theme }) => theme.primary), // Can you get into props.theme?
    warning: ({ theme }) => theme.warning),
    info: ({ theme }) => theme.info),
    default: 'white',
  },
};
```

**Comment by scf4** [comment]
Hi @udielenberg, this works just fine. Thanks!
