### ISSUE TITLE
Use actual tagged template literals instead of pseudo syntax

### ISSUE THREAD

**Issue by sethcalebweeks** [scf4/styled-map#15]
The pseudo syntax used does not allow use of JavaScript variables within the string. For example, the following does not work:

```javascript
const buttonColor = styledMap`
  primary: ${primary};
  warning: ${warning};
  info: ${info};
  default: #ccc;
`;
```

**Comment by scf4** [comment]
@weeksseth this is supposed to work. I’ll look into this immediately

**Comment by scf4** [comment]
@weeksseth Can you post the full code you're using. I can't replicate this.

All of this works fine: https://gist.github.com/scf4/5b8e79e1ba10c431d8f2dd70a2bb561b

**Comment by sethcalebweeks** [comment]
Yep, you're right, it works. I made a mistake. Thanks for your work on this! It's an awesome project!
