### ISSUE TITLE
Ability to use prop values in mapToTheme

### ISSUE THREAD

**Issue by mmartinsky** [scf4/styled-map#17]
I think it's similar to #8 , but it would be nice to be able to use the prop value rather than just prop key in mapToTheme.

So mapToTheme would become something like:
```
export const mapToTheme = (themeKey, propValue) => 
```

Ideal Example:

```
const theme = {
    color: {
        primary: '#086ea1',
        success: '#178c5b',
        warning: '#D9822B',
        danger: '#DB3737',
    },
};

const StyledButton = styled.button`
    color: ${mapToTheme('color', 'kind')};
`}

<Button kind='success' />
```

I'd be happy to submit a PR if you agree this would be helpful

**Comment by sergeylaptev** [comment]
Any updates on this?

**Comment by mmartinsky** [comment]
Added a PR in #19, please let me know what you think @scf4 ?

**Comment by smoliakov** [comment]
Definitely very useful feature, please, include in next release @scf4

**Comment by scf4** [comment]
Will include in next release after reviewing the PR, thanks @mmartinsky
