### ISSUE TITLE
Rerelease

### ISSUE THREAD

**Issue by jaszczw** [scf4/styled-map#18]
Hey, could you release current state of the master - as far as I can tell the lib no longer has dependency to babel-preset that was introduced between 3.0.0 and 3.2.0.

**Comment by scf4** [comment]
hi @jaszczw, could you clarify what the issue is?

**Comment by jaszczw** [comment]
Currently npm version of the package has a dependency to babel instead of devDependency small change :)

**Comment by scf4** [comment]
Ah I see, thanks I'll fix it this week!

**Comment by scf4** [comment]
The latest version was still rc, should be fine now!
