### ISSUE TITLE
please fix 'var mapOfStyles = args.pop();'

### ISSUE THREAD

**Issue by anilpixel** [scf4/styled-map#2]
When I render two components.

```
var mapOfStyles = args.pop();

// here will modify args's value. after next component render, args is empty and throw an error.

```
I am sorry for my poor english. @scf4 .

**Comment by scf4** [comment]
Thanks I'll look into this right away

**Comment by linayanse** [comment]
@scf4 thanks.

**Comment by scf4** [comment]
Pushed to NPM. Thank you again, that was a terrible oversight on my part.
