### ISSUE TITLE
Using in Conjunction with Polished

### ISSUE THREAD

**Issue by ghost** [scf4/styled-map#25]
I have the following object:

```
export const colorProps = styledMap({
  default: yellow,
  primary: blue,
  secondary: green,
})
```

I use it as follows:

```
background-color: ${colorProps};
```

Everything works fine.  

But now I would like to use [polished](https://polished.js.org/) to darken the background-color on hover -- something like this:

```
&:hover {
    background-color: ${darken(0.1, colorProps)};
      }
```

But this does not work.  It throws an error.

```
Error: Passed an incorrect argument to a color function, please pass a string representation of a color.
```

Any suggestions, therefore, of how I can use styled-map in conjunction with polished?

**Comment by scf4** [comment]
See README.md
