### ISSUE TITLE
Access props in styledMap function parameters

### ISSUE THREAD

**Issue by sstefoss** [scf4/styled-map#6]
Hey, i see it's not possible to access `props` inside styledMap. 
Eg. I would like to access `theme` like this:

```
const color = styledMap({
  primary: props => props.theme.color.primary
  warning: ...,
  danger: ...,
});
```

If it is useful i can PR.

**Comment by scf4** [comment]
Take a look at the new syntax for v3 of `styled-map`: https://github.com/scf4/styled-map/blob/newsyntax/README.md

You'll be able to do this:

```js
const color = styledMap`
  primary: ${props => props.theme.color.primary};
  warning: orange;
  danger: #c00;
`;
```

The beta will be on NPM later this week.

**Comment by sstefoss** [comment]
Yes, that would work!
