### ISSUE TITLE
Release v3

### ISSUE THREAD

**Issue by brabeji** [scf4/styled-map#9]
Hello @scf4!

I like the v3 very much. Is there any ETA to publish it? I'm using the code without changes and it works pretty good.

Thank you for this lib, cheers!

**Comment by scf4** [comment]
Hi @brabeji, 3.0.0 should be the latest on NPM: https://www.npmjs.com/package/styled-map

**Comment by brabeji** [comment]
Awesome, didn't check the npm as last release here is 2.0. Thanks again! :)
